<?php 
session_start();

if (!isset($_SESSION['attempt_logged_in']) AND !isset($_SESSION['register_email'])) {
    $_SESSION['login_error'] = "You need to sign in";
    header('Location: index.php');
    exit();
}
?>

<!DOCTYPE html>
<html>

<?php include_once '../private/header.php'; ?>

<body>
    <div class="otp-container">
    <div>
        <div class="logo">
            <img src="assets/images/UoS_Logo_BLACK.png" alt="University of Sunderland Logo" style="width: 175px">
        </div>    
        <h2>Enter TOTP Code</h2>
        <p>that is generated by your chosen authenticator app.</p>
        <form action="../private/totp_verification.php" method="post">
            <div id="otpErrorMessage" style="background: #FF3535; border-radius: 3px;">
            <!-- error message -->
            <?php
                if (isset($_SESSION['totp_error'])) : ?>   
                <p style="color: white; font-size: 10px;"><?= $_SESSION['totp_error']; unset($_SESSION['totp_error']);?></p>
            <?php endif ?>
            <!-- /error message -->
            </div>
            <div class="otp-fields">
            <input type="text" name="otp1" maxlength="1" autocomplete="off" autofocus required>
            <input type="text" name="otp2" maxlength="1" autocomplete="off" required>
            <input type="text" name="otp3" maxlength="1" autocomplete="off" required>
            <input type="text" name="otp4" maxlength="1" autocomplete="off" required>
            <input type="text" name="otp5" maxlength="1" autocomplete="off" required>
            <input type="text" name="otp6" maxlength="1" autocomplete="off" required>
            </div>
            <button type="submit" name="submit" class="verifybutton">Verify</button>
        </form>
    </div>
    </div>
    <script>
         <?php include 'assets/script.js'; ?>
    </script>
</body>
</html>